/** Consumer .gitignore for generated SDK out dirs. No extra deps. */

import fs from "node:fs";
import path from "node:path";

export const GITIGNORE_FILE = ".gitignore";

/** Default ignore rules so a committed SDK does not pick up build junk. */
export const DEFAULT_GITIGNORE = [
  "# Generated by sdk-mcp-gen. Overwritten on each generate.",
  "__pycache__/",
  "*.pyc",
  "node_modules/",
  ".DS_Store",
  "*.egg-info/",
  "",
].join("\n");

/**
 * Always overwrite .gitignore (generated artifact).
 * Returns [".gitignore"].
 */
export function writeGitignoreArtifact(absOut) {
  const text = DEFAULT_GITIGNORE.endsWith("\n") ? DEFAULT_GITIGNORE : DEFAULT_GITIGNORE + "\n";
  fs.writeFileSync(path.join(absOut, GITIGNORE_FILE), text);
  return [GITIGNORE_FILE];
}

/** Drop leftover generated .gitignore when --no-gitignore. */
export function removeGitignoreArtifact(absOut) {
  const p = path.join(absOut, GITIGNORE_FILE);
  try {
    if (fs.existsSync(p) && fs.statSync(p).isFile()) fs.unlinkSync(p);
  } catch {
    /* ignore */
  }
}
